repositories:
- name: "cos-toolkit-teal"
  url: "quay.io/costoolkit/releases-teal"
  type: "docker"
  github: "https://github.com/rancher-sandbox/cOS-toolkit"
- name: "cos-toolkit-teal-arm64"
  url: "quay.io/costoolkit/releases-teal-arm64"
  type: "docker"
  github: "https://github.com/rancher-sandbox/cOS-toolkit"

BaseUrl: "https://rancher-sandbox.github.io/cos-toolkit-package-browser"
