repositories:
- name: "cos-toolkit-green"
  url: "quay.io/costoolkit/releases-green"
  type: "docker"
  github: "https://github.com/rancher-sandbox/cOS-toolkit"
- name: "cos-toolkit-green-arm64"
  url: "quay.io/costoolkit/releases-green-arm64"
  type: "docker"
  github: "https://github.com/rancher-sandbox/cOS-toolkit"
