repositories:
- name: "cos-toolkit-teal"
  url: "quay.io/costoolkit/releases-teal"
  type: "docker"
  github: "https://github.com/rancher-sandbox/cOS-toolkit"
- name: "cos-toolkit-teal-arm64"
  url: "quay.io/costoolkit/releases-teal-arm64"
  type: "docker"
  github: "https://github.com/rancher-sandbox/cOS-toolkit"
- name: "cos-toolkit-green"
  url: "quay.io/costoolkit/releases-green"
  type: "docker"
  github: "https://github.com/rancher-sandbox/cOS-toolkit"
- name: "cos-toolkit-green-arm64"
  url: "quay.io/costoolkit/releases-green-arm64"
  type: "docker"
  github: "https://github.com/rancher-sandbox/cOS-toolkit"
- name: "cos-toolkit-blue"
  url: "quay.io/costoolkit/releases-blue"
  type: "docker"
  github: "https://github.com/rancher-sandbox/cOS-toolkit"
- name: "cos-toolkit-blue-arm64"
  url: "quay.io/costoolkit/releases-blue-arm64"
  type: "docker"
  github: "https://github.com/rancher-sandbox/cOS-toolkit"
- name: "cos-toolkit-orange"
  url: "quay.io/costoolkit/releases-orange"
  type: "docker"
  github: "https://github.com/rancher-sandbox/cOS-toolkit"
- name: "cos-toolkit-orange-arm64"
  url: "quay.io/costoolkit/releases-orange-arm64"
  type: "docker"
  github: "https://github.com/rancher-sandbox/cOS-toolkit"
BaseUrl: "https://rancher-sandbox.github.io/cos-toolkit-package-browser"
